### PR TITLE
fix(vitest-environment-nuxt): import `@testing-library/vue` within `renderSuspended`

### LINKED ISSUE #330: `@testing-render/vue` is needed when using a util
````
import * as _testing_library_vue from '@testing-library/vue';
import { RenderOptions as RenderOptions$1 } from '@testing-library/vue';
````

is being inlined in `vitest-environment-nuxt/dist/utils`, forcing the user to install `@testing-library/vue` if they use any utils provided by `vitest-environment-nuxt` even if they don't use `renderSuspended()`

### PR DESCRIPTION
**Pull request by huang-julien**
Hi :wave: 

This PR resolves #330 , this removes the import from `@testing-library/vue` in the final build of the utils file

### CODE REVIEW

File: packages/vitest-environment-nuxt/src/runtime/render.ts [hunk 1]
```diff
@@ -68,6 +67,8 @@ export async function renderSuspended<T>(
     ..._options
   } = options || {}
 
+  const { render : renderFromTestingLibrary } = await importModule<typeof import('@testing-library/vue')>('@testing-library/vue')
```
Comment (danielroe) [inline packages/vitest-environment-nuxt/src/runtime/render.ts:70]: could we just use a dynamic import of `@testing-library/vue` rather than `importModule`?

Comment (huang-julien) [reply packages/vitest-environment-nuxt/src/runtime/render.ts:70]: sure :+1:

**Review by danielroe — APPROVED** [review]
